package laporan;
import fungsi.koneksiDB;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

public class DlgRL4A extends javax.swing.JDialog {
    private final validasi Valid=new validasi();
    private final Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2,ps3,ps4,ps5;
    private ResultSet rs,rs2,rs4,rs5;
    private StringBuilder htmlContent;
    private int hr0s7l=0,hr0s7p=0,hr0s7=0,hr8s28l=0,hr8s28p=0,hr8s28=0,hr0s1thl=0,hr0s1thp=0,hr0s1th=0,th1s4l=0,th1s4p=0,th1s4=0,th5s9l=0,th5s9p=0,th5s9=0,
                th10s14l=0,th10s14p=0,th10s14=0,th15s19l=0,th15s19p=0,th15s19=0,th20s44l=0,th20s44p=0,th20s44,th45s54l=0,th45s54p=0,th45s54,th55s59l=0,th55s59p=0,th55s59,th60s69l=0,th60s69p=0,th60s69,lbth70l=0,lbth70p=0,lbth70=0,mati=0,pasienTNI=0,angkatanLain=0;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgRL4A(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML1.setEditable(true);
        LoadHTML1.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML1.setDocument(doc);
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    private int i=0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        TabRawat = new javax.swing.JTabbedPane();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();
        Scroll1 = new widget.ScrollPane();
        LoadHTML1 = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ RL 4A Data Keadaan Morbiditas Pasien Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        TabRawat.setBackground(new java.awt.Color(255, 255, 253));
        TabRawat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TabRawat.setName("TabRawat"); // NOI18N
        TabRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabRawatMouseClicked(evt);
            }
        });

        Scroll.setBorder(null);
        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        TabRawat.addTab("Berdasar Tanggal Masuk", Scroll);

        Scroll1.setBorder(null);
        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        LoadHTML1.setBorder(null);
        LoadHTML1.setName("LoadHTML1"); // NOI18N
        Scroll1.setViewportView(LoadHTML1);

        TabRawat.addTab("Berdasar Tanggal Keluar", Scroll1);

        internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#323232;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
            );
            bg.close();
            
            File f = new File("rl4a.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));
            if(TabRawat.getSelectedIndex()==0){
                bw.write(LoadHTML.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                        "<div style='width: max-content;'>"+
                            "<p>DATASEMEN KESEHATAN WILAYAH 13.04.02 PALU <br> RUMAH SAKIT III 13.06.01 DR. SINDHU TRISNO</p>"+
                            "<hr style='border:none; height:2px; background-color:#999;'>"+
                        "</div>"+
                        "</hr>"+
                        "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                            "<tr class='isi2'>"+
                                "<td valign='top' align='center'>"+
                                    "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                "</td>"+
                           "</tr>"+
                        "</table>")
                );
                bw.close();
            }else if(TabRawat.getSelectedIndex()==1){
                bw.write(LoadHTML1.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                            "<div style='width: max-content;'>"+
                                "<p>DATASEMEN KESEHATAN WILAYAH 13.04.02 PALU <br> RUMAH SAKIT III 13.06.01 DR. SINDHU TRISNO</p>"+
                                "<hr style='border:none; height:2px; background-color:#999;'>"+
                            "</div>"+
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                                "<tr class='isi2'>"+
                                    "<td valign='top' align='center'>"+
                                        "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                    "</td>"+
                               "</tr>"+
                            "</table>")
                );
                bw.close();
            }                
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,Tgl2,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,Tgl1);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void TabRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRawatMouseClicked
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }
    }//GEN-LAST:event_TabRawatMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRL4A dialog = new DlgRL4A(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.editorpane LoadHTML1;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private javax.swing.JTabbedPane TabRawat;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%' rowspan='2'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='2'>Kode ICD 10</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='18%' rowspan='2'>Jenis Penyakit</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='2'>Menurut Golongan Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='45%' colspan='12'>Golongan Umur(Tahun)</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='3'>Total Kunjungan</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='2'>Meninggal</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>Pasien TNI</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>Pasien Lainnya</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>0-7 hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>8-28hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>< 1th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>1-4th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>5-9th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>10-14th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>15-19th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>20-44th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>45-54th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>55-59th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>60-69th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>70+</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='1'>Lk</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='1'>Pr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='1'>Jumlah</td>"+
                "</tr>"+
//                "<tr class='isi'>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>1</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>2</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>3</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>4</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>5</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>6</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>7</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>8</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>9</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>10</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>11</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>12</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>13</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>14</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>15</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>16</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>17</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>18</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>19</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>20</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>21</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>22</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>23</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>24</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>25</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("select diagnosa_pasien.kd_penyakit,SUBSTRING(penyakit.nm_penyakit,1,80) as nm_penyakit from diagnosa_pasien inner join penyakit "+
                    "inner join reg_periksa on diagnosa_pasien.kd_penyakit=penyakit.kd_penyakit and reg_periksa.no_rawat=diagnosa_pasien.no_rawat "+
                    "where diagnosa_pasien.status='Ranap' and reg_periksa.tgl_registrasi between ? and ? and (left(diagnosa_pasien.kd_penyakit,1)<>'V' or "+
                    " left(diagnosa_pasien.kd_penyakit,1)<>'W' or left(diagnosa_pasien.kd_penyakit,1)<>'X' or left(diagnosa_pasien.kd_penyakit,1)<>'Y') "+
                    " group by diagnosa_pasien.kd_penyakit order by diagnosa_pasien.kd_penyakit");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    hr0s7l=0;hr0s7p=0;hr0s7=0;hr8s28l=0;hr8s28p=0;hr8s28=0;hr0s1thl=0;hr0s1thp=0;hr0s1th=0;th1s4l=0;th1s4p=0;th1s4=0;th5s9l=0;th5s9p=0;th5s9=0;
                    th10s14l=0;th10s14p=0;th10s14=0;th15s19l=0;th15s19p=0;th15s19=0;th20s44l=0;th20s44p=0;th20s44=0;th45s54l=0;th45s54p=0;th45s54=0;th55s59l=0;th55s59p=0;th55s59=0;th60s69l=0;th60s69p=0;th60s69=0;lbth70l=0;lbth70p=0;lbth70=0;mati=0;pasienTNI=0;angkatanLain=0;
                    ps2=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "where diagnosa_pasien.status='Ranap' "+
                            "and reg_periksa.tgl_registrasi between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    ps4=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk,pasien_tni.golongan_tni,golongan_tni.nama_golongan "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join pasien_tni inner join golongan_tni "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis and reg_periksa.no_rkm_medis=pasien_tni.no_rkm_medis and pasien_tni.golongan_tni=golongan_tni.id "+
                            "where diagnosa_pasien.status='Ranap' "+
                            "and reg_periksa.tgl_registrasi between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    try {
                        ps4.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps4.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps4.setString(3,rs.getString("kd_penyakit"));
                        rs4=ps4.executeQuery();
                        while(rs4.next()){
                            if(rs4.getString("nama_golongan").equals("TNI AD")){
                                pasienTNI++;
                            }
                        }
                        ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps2.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps2.executeQuery();
                        while(rs2.next()){
                            if(rs2.getString("sttsumur").equals("Hr")){
                                if((rs2.getInt("umurdaftar")>=0)&&(rs2.getInt("umurdaftar")<=7)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr0s7l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr0s7p++;
                                    }
                                    hr0s7++;
                                }else if((rs2.getInt("umurdaftar")>=7)&&(rs2.getInt("umurdaftar")<=28)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr8s28l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr8s28p++;
                                    }
                                    hr8s28++;
                                }else if(rs2.getInt("umurdaftar")>28){
                                    if(rs2.getString("jk").equals("L")){
                                        hr0s1thl++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr0s1thp++;
                                    }
                                    hr0s1th++;
                                }
                            }else if(rs2.getString("sttsumur").equals("Bl")){
                                if(rs2.getString("jk").equals("L")){
                                    hr0s1thl++;
                                }else if(rs2.getString("jk").equals("P")){
                                    hr0s1thp++;
                                }
                                hr0s1th++;
                            }else if(rs2.getString("sttsumur").equals("Th")){
                                if((rs2.getInt("umurdaftar")>=0)&&(rs2.getInt("umurdaftar")<=4)){
                                    if(rs2.getString("jk").equals("L")){
                                        th1s4l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th1s4p++;
                                    }
                                    th1s4++;
                                }else if((rs2.getInt("umurdaftar")>=5)&&(rs2.getInt("umurdaftar")<=14)){
                                    if(rs2.getString("jk").equals("L")){
                                        th5s9l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th5s9p++;
                                    }
                                    th5s9++;
                                }else if((rs2.getInt("umurdaftar")>=15)&&(rs2.getInt("umurdaftar")<=24)){
                                    if(rs2.getString("jk").equals("L")){
                                        th10s14l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th10s14p++;
                                    }
                                    th10s14++;
                                }else if((rs2.getInt("umurdaftar")>=25)&&(rs2.getInt("umurdaftar")<=44)){
                                    if(rs2.getString("jk").equals("L")){
                                        th15s19l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th15s19p++;
                                    }
                                    th15s19++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th20s44l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th20s44p++;
                                    }
                                    th20s44++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th45s54l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th45s54p++;
                                    }
                                    th45s54++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th55s59l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th55s59p++;
                                    }
                                    th55s59++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th60s69l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th60s69p++;
                                    }
                                    th60s69++;
                                }else if(rs2.getInt("umurdaftar")>=65){
                                    if(rs2.getString("jk").equals("L")){
                                        lbth70l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        lbth70p++;
                                    }
                                    lbth70++;
                                }
                            }
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 1 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    
                    ps3=koneksi.prepareStatement(
                            "select count(pasien_mati.no_rkm_medis) "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join pasien_mati "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and pasien_mati.no_rkm_medis=pasien.no_rkm_medis where diagnosa_pasien.status='Ranap' "+
                            "and reg_periksa.tgl_registrasi between ? and ? and diagnosa_pasien.kd_penyakit=? "+
                            "group by diagnosa_pasien.kd_penyakit");
                    try {
                        ps3.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps3.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps3.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps3.executeQuery();
                        while(rs2.next()){
                            mati=rs2.getInt(1);
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 2 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kd_penyakit")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+pasienTNI+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7l+hr0s1thl+hr8s28l+th1s4l+th5s9l+th10s14l+th15s19l+th20s44l+th45s54l+th55s59l+th60s69l+lbth70l+hr0s7p+hr8s28p+hr0s1thp+th1s4p+th5s9p+th10s14p+th15s19p+th20s44p+th45s54p+th55s59p+th60s69p+lbth70p-pasienTNI)+"</td>"+
                            "<td valign='middle' align='center'>"+hr0s7+"</td>"+
//                            "<td valign='middle' align='center'>"+hr0s7p+"</td>"+
                            "<td valign='middle' align='center'>"+hr8s28+"</td>"+ 
//                            "<td valign='middle' align='center'>"+hr8s28p+"</td>"+
                            "<td valign='middle' align='center'>"+hr0s1th+"</td>"+ 
//                            "<td valign='middle' align='center'>"+hr0s1thp+"</td>"+
                            "<td valign='middle' align='center'>"+th1s4+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th1s4p+"</td>"+  
                            "<td valign='middle' align='center'>"+th5s9+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th5s9p+"</td>"+
                            "<td valign='middle' align='center'>"+th10s14+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th10s14p+"</td>"+
                            "<td valign='middle' align='center'>"+th15s19+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th15s19p+"</td>"+
                            "<td valign='middle' align='center'>"+th20s44+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th20s44p+"</td>"+
                            "<td valign='middle' align='center'>"+th45s54+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th45s54p+"</td>"+
                            "<td valign='middle' align='center'>"+th55s59+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th55s59p+"</td>"+
                            "<td valign='middle' align='center'>"+th60s69+"</td>"+ 
//                            "<td valign='middle' align='center'>"+th60s69p+"</td>"+
                            "<td valign='middle' align='center'>"+lbth70+"</td>"+ 
//                            "<td valign='middle' align='center'>"+lbth70p+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7l+hr8s28+hr0s1thl+th1s4l+th5s9l+th10s14l+th15s19l+th20s44l+th45s54l+th55s59l+th60s69l+lbth70l)+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7p+hr8s28p+hr0s1thp+th1s4p+th5s9p+th10s14p+th15s19p+th20s44p+th45s54p+th55s59p+th60s69p+lbth70p)+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7l+hr0s1thl+hr8s28l+th1s4l+th5s9l+th10s14l+th15s19l+th20s44l+th45s54l+th55s59l+th60s69l+lbth70l+hr0s7p+hr8s28p+hr0s1thp+th1s4p+th5s9p+th10s14p+th15s19p+th20s44p+th45s54p+th55s59p+th60s69p+lbth70p-mati)+"</td>"+
                            "<td valign='middle' align='center'>"+mati+"</td>"+
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgRL4A.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "<table style=\"width:100%; margin-top: 20px\">\n" +
                        "<tr>" +
                            "<td style=\"width:50%;\"></td>\n" +
                            "<td style=\"width:50%;\">\n" +
                                "<div style=\"text-align: center;\">\n" +
                                    "<p style=\"height: 2px\">\n" +
                                        "Kepala Rumkit Tk.III 13.06.01\n" +
                                    "</p>\n" +
                                    "<p style=\"height: 2px; margin-bottom: 15px\">\n" +
                                        "dr. Sindhu Trisno\n" +
                                    "</p>\n" +
                                    "<p style=\"height: 70px\"></p>\n" +
                                    "<p style=\"height: 2px; margin-top: 15px\">\n" +
                                        "drg. Hengki Yudhana, Sp.KG\n" +
                                    "</p>\n" +
                                    "<p style=\"height: 2px\">\n" +
                                        "Letkol Ckm NRP 11020015731276\n" +
                                    "</p>\n" +
                                "</div>\n" +
                            "</td>\n" +
                        "</tr>\n" +
                    "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    private void prosesCari2() {
       this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%' rowspan='2'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='2'>Kode ICD 10</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='18%' rowspan='2'>Jenis Penyakit</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='2'>Menurut Golongan Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='45%' colspan='12'>Golongan Umur(Tahun)</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='3'>Total Kunjungan</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='2'>Meninggal</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>Pasien TNI</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>Pasien Lainnya</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>0-7 hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>8-28hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>< 1th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>1-4th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>5-9th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>10-14th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>15-19th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>20-44th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>45-54th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>55-59th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>60-69th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='1'>70+</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='1'>Lk</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='1'>Pr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='1'>Jumlah</td>"+
                "</tr>"+
//                "<tr class='isi'>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
//                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>1</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>2</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>3</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>4</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>5</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>6</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>7</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>8</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>9</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>10</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>11</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>12</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>13</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>14</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>15</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>16</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>17</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>18</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>19</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>20</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>21</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>22</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>23</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>24</td>"+
//                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>25</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("select diagnosa_pasien.kd_penyakit,SUBSTRING(penyakit.nm_penyakit,1,80) as nm_penyakit from diagnosa_pasien inner join penyakit "+
                    "inner join reg_periksa inner join kamar_inap on diagnosa_pasien.kd_penyakit=penyakit.kd_penyakit and reg_periksa.no_rawat=diagnosa_pasien.no_rawat "+
                    "and kamar_inap.no_rawat=reg_periksa.no_rawat where diagnosa_pasien.status='Ranap' and diagnosa_pasien.prioritas='1' and "+
                    " kamar_inap.tgl_keluar between ? and ? and (left(diagnosa_pasien.kd_penyakit,1)<>'V' or left(diagnosa_pasien.kd_penyakit,1)<>'W' or "+
                    " left(diagnosa_pasien.kd_penyakit,1)<>'X' or left(diagnosa_pasien.kd_penyakit,1)<>'Y') group by diagnosa_pasien.kd_penyakit order by diagnosa_pasien.kd_penyakit");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    hr0s7l=0;hr0s7p=0;hr0s7=0;hr8s28l=0;hr8s28p=0;hr8s28=0;hr0s1thl=0;hr0s1thp=0;hr0s1th=0;th1s4l=0;th1s4p=0;th1s4=0;th5s9l=0;th5s9p=0;th5s9=0;
                    th10s14l=0;th10s14p=0;th10s14=0;th15s19l=0;th15s19p=0;th15s19=0;th20s44l=0;th20s44p=0;th20s44=0;th45s54l=0;th45s54p=0;th45s54=0;th55s59l=0;th55s59p=0;th55s59=0;th60s69l=0;th60s69p=0;th60s69=0;lbth70l=0;lbth70p=0;lbth70=0;mati=0;pasienTNI=0;angkatanLain=0;
                    ps2=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join kamar_inap "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and kamar_inap.no_rawat=reg_periksa.no_rawat where diagnosa_pasien.status='Ranap' "+
                            "and kamar_inap.tgl_keluar between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    ps5=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk,pasien_tni.golongan_tni,golongan_tni.nama_golongan "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join kamar_inap inner join pasien_tni inner join golongan_tni "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis and reg_periksa.no_rkm_medis=pasien_tni.no_rkm_medis and pasien_tni.golongan_tni=golongan_tni.id and kamar_inap.no_rawat=reg_periksa.no_rawat "+
                            "where diagnosa_pasien.status='Ranap' "+
                            "and kamar_inap.tgl_keluar between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    try {
                        ps5.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps5.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps5.setString(3,rs.getString("kd_penyakit"));
                        rs5=ps5.executeQuery();
                        while(rs5.next()){
                            if(rs5.getString("nama_golongan").equals("TNI AD")){
                                pasienTNI++;
                            }
                        }
                        ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps2.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps2.executeQuery();
                        while(rs2.next()){
                            if(rs2.getString("sttsumur").equals("Hr")){
                                if((rs2.getInt("umurdaftar")>=0)&&(rs2.getInt("umurdaftar")<=6)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr0s7l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr0s7p++;
                                    }
                                     hr0s7++;
                                }else if((rs2.getInt("umurdaftar")>=7)&&(rs2.getInt("umurdaftar")<=28)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr8s28l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr8s28p++;
                                    }
                                     hr8s28++;
                                }else if(rs2.getInt("umurdaftar")>28){
                                    if(rs2.getString("jk").equals("L")){
                                        hr0s1thl++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr0s1thp++;
                                    }
                                    hr0s1th++;
                                }
                            }else if(rs2.getString("sttsumur").equals("Bl")){
                                if(rs2.getString("jk").equals("L")){
                                    hr0s1thl++;
                                }else if(rs2.getString("jk").equals("P")){
                                    hr0s1thp++;
                                }
                                hr0s1th++;
                            }else if(rs2.getString("sttsumur").equals("Th")){
                                if((rs2.getInt("umurdaftar")>=0)&&(rs2.getInt("umurdaftar")<=4)){
                                    if(rs2.getString("jk").equals("L")){
                                        th1s4l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th1s4p++;
                                    }
                                    th1s4++;
                                }else if((rs2.getInt("umurdaftar")>=5)&&(rs2.getInt("umurdaftar")<=14)){
                                    if(rs2.getString("jk").equals("L")){
                                        th5s9l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th5s9p++;
                                    }
                                    th5s9++;
                                }else if((rs2.getInt("umurdaftar")>=15)&&(rs2.getInt("umurdaftar")<=24)){
                                    if(rs2.getString("jk").equals("L")){
                                        th10s14l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th10s14p++;
                                    }
                                    th10s14++;
                                }else if((rs2.getInt("umurdaftar")>=25)&&(rs2.getInt("umurdaftar")<=44)){
                                    if(rs2.getString("jk").equals("L")){
                                        th15s19l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th15s19p++;
                                    }
                                    th15s19++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th20s44l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th20s44p++;
                                    }
                                    th20s44++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th45s54l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th45s54p++;
                                    }
                                    th45s54++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th55s59l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th55s59p++;
                                    }
                                    th55s59++;
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th60s69l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th60s69p++;
                                    }
                                    th60s69++;
                                }else if(rs2.getInt("umurdaftar")>=65){
                                    if(rs2.getString("jk").equals("L")){
                                        lbth70l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        lbth70p++;
                                    }
                                    lbth70++;
                                }
                            }
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 1 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    
                    ps3=koneksi.prepareStatement(
                            "select count(pasien_mati.no_rkm_medis) "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join pasien_mati inner join kamar_inap "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and pasien_mati.no_rkm_medis=pasien.no_rkm_medis where diagnosa_pasien.status='Ranap' and kamar_inap.no_rawat=reg_periksa.no_rawat "+
                            "and kamar_inap.tgl_keluar between ? and ? and diagnosa_pasien.kd_penyakit=? "+
                            "group by diagnosa_pasien.kd_penyakit");
                    try {
                        ps3.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps3.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps3.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps3.executeQuery();
                        while(rs2.next()){
                            mati=rs2.getInt(1);
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 2 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kd_penyakit")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+pasienTNI+"</td>"+
//                            "<td valign='middle' align='center'>"+hr0s7p+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7l+hr0s1thl+hr8s28l+th1s4l+th5s9l+th10s14l+th15s19l+th20s44l+th45s54l+th55s59l+th60s69l+lbth70l+hr0s7p+hr8s28p+hr0s1thp+th1s4p+th5s9p+th10s14p+th15s19p+th20s44p+th45s54p+th55s59p+th60s69p+lbth70p-pasienTNI)+"</td>"+
//                            "<td valign='middle' align='center'>"+hr8s28p+"</td>"+
                            "<td valign='middle' align='center'>"+hr0s7+"</td>"+
//                          "<td valign='middle' align='center'>"+hr0s7p+"</td>"+
                            "<td valign='middle' align='center'>"+hr8s28+"</td>"+ 
//                            "<td valign='middle' align='center'>"+hr8s28p+"</td>"+
                            "<td valign='middle' align='center'>"+hr0s1th+"</td>"+
//                            "<td valign='middle' align='center'>"+hr0s1thp+"</td>"+
                            "<td valign='middle' align='center'>"+th1s4+"</td>"+
//                            "<td valign='middle' align='center'>"+th1s4p+"</td>"+
                            "<td valign='middle' align='center'>"+th5s9+"</td>"+
//                            "<td valign='middle' align='center'>"+th5s9p+"</td>"+
                            "<td valign='middle' align='center'>"+th10s14+"</td>"+
//                            "<td valign='middle' align='center'>"+th10s14p+"</td>"+
                            "<td valign='middle' align='center'>"+th15s19+"</td>"+
//                            "<td valign='middle' align='center'>"+th15s19p+"</td>"+
                            "<td valign='middle' align='center'>"+th20s44+"</td>"+
//                            "<td valign='middle' align='center'>"+th20s44p+"</td>"+
                            "<td valign='middle' align='center'>"+th45s54+"</td>"+
//                            "<td valign='middle' align='center'>"+th45s54p+"</td>"+
                            "<td valign='middle' align='center'>"+th55s59+"</td>"+
//                            "<td valign='middle' align='center'>"+th55s59p+"</td>"+
                            "<td valign='middle' align='center'>"+th60s69+"</td>"+
//                            "<td valign='middle' align='center'>"+th60s69p+"</td>"+
                            "<td valign='middle' align='center'>"+lbth70+"</td>"+
//                            "<td valign='middle' align='center'>"+lbth70p+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7l+hr0s1thl+hr8s28l+th1s4l+th5s9l+th10s14l+th15s19l+th20s44l+th45s54l+th55s59l+th60s69l+lbth70l)+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7p+hr8s28p+hr0s1thp+th1s4p+th5s9p+th10s14p+th15s19p+th20s44p+th45s54p+th55s59p+th60s69p+lbth70p)+"</td>"+
                            "<td valign='middle' align='center'>"+(hr0s7l+hr0s1thl+hr8s28l+th1s4l+th5s9l+th10s14l+th15s19l+th20s44l+th45s54l+th55s59l+th60s69l+lbth70l+hr0s7p+hr8s28p+hr0s1thp+th1s4p+th5s9p+th10s14p+th15s19p+th20s44p+th45s54p+th55s59p+th60s69p+lbth70p-mati)+"</td>"+
                            "<td valign='middle' align='center'>"+mati+"</td>"+
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgRL4A.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML1.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                              "<table style=\"width:100%; margin-top: 20px\">\n" +
                        "<tr>" +
                            "<td style=\"width:50%;\"></td>\n" +
                            "<td style=\"width:50%;\">\n" +
                                "<div style=\"text-align: center;\">\n" +
                                    "<p style=\"height: 2px\">\n" +
                                        "Kepala Rumkit Tk.III 13.06.01\n" +
                                    "</p>\n" +
                                    "<p style=\"height: 2px; margin-bottom: 15px\">\n" +
                                        "dr. Sindhu Trisno\n" +
                                    "</p>\n" +
                                    "<p style=\"height: 70px\"></p>\n" +
                                    "<p style=\"height: 2px; margin-top: 15px\">\n" +
                                        "drg. Hengki Yudhana, Sp.KG\n" +
                                    "</p>\n" +
                                    "<p style=\"height: 2px\">\n" +
                                        "Letkol Ckm NRP 11020015731276\n" +
                                    "</p>\n" +
                                "</div>\n" +
                            "</td>\n" +
                        "</tr>\n" +
                    "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());        
    }
    
    
    
    public void isCek(){
        BtnPrint.setEnabled(akses.getrl4asebab());
    }
    
}
