/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgKamar.java
 *
 * Created on May 23, 2010, 12:07:21 AM
 */

package bridging;

import fungsi.akses;
import java.awt.Cursor;
import fungsi.sekuel;

/**
 *
 * @author dosen
 */
public final class PassphraseBSRE extends javax.swing.JDialog {
   private int lebar=0,tinggi=0;
   private sekuel Sequel=new sekuel();
   private String noka="";

    /** Creates new form DlgKamar
     * @param parent
     * @param modal */
    public PassphraseBSRE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        internalFrame1 = new widget.InternalFrame();
        PassphraseBSRE = new javax.swing.JLabel();
        TPassphrase = new widget.TextBox();
        panelGlass6 = new widget.panelisi();
        BtnKeluar = new widget.Button();
        BtnSimpanTTE = new widget.Button();

        jTextField1.setText("jTextField1");
        jTextField1.setName("jTextField1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Self Sign ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        PassphraseBSRE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PassphraseBSRE.setForeground(new java.awt.Color(50, 50, 50));
        PassphraseBSRE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassphraseBSRE.setText("Passphrase/OTP");
        PassphraseBSRE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PassphraseBSRE.setInheritsPopupMenu(false);
        PassphraseBSRE.setName("PassphraseBSRE"); // NOI18N
        PassphraseBSRE.setPreferredSize(new java.awt.Dimension(85, 56));
        internalFrame1.add(PassphraseBSRE, java.awt.BorderLayout.PAGE_START);

        TPassphrase.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TPassphrase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TPassphrase.setHighlighter(null);
        TPassphrase.setMargin(new java.awt.Insets(5, 9, 5, 9));
        TPassphrase.setMinimumSize(new java.awt.Dimension(16, 16));
        TPassphrase.setName("TPassphrase"); // NOI18N
        TPassphrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPassphraseActionPerformed(evt);
            }
        });
        internalFrame1.add(TPassphrase, java.awt.BorderLayout.CENTER);
        TPassphrase.getAccessibleContext().setAccessibleName("TPassphrase");

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 54));
        panelGlass6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Nanti");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnKeluar);

        BtnSimpanTTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png")));
        BtnSimpanTTE.setMnemonic('T');
        BtnSimpanTTE.setToolTipText("Alt+T");
        BtnSimpanTTE.setLabel("Simpan TTE");
        BtnSimpanTTE.setName("BtnSimpanTTE"); // NOI18N
        BtnSimpanTTE.setPreferredSize(new java.awt.Dimension(150, 30));
        BtnSimpanTTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanTTEActionPerformed(evt);
            }
        });
        panelGlass6.add(BtnSimpanTTE);
        BtnSimpanTTE.getAccessibleContext().setAccessibleName("");

        getContentPane().add(panelGlass6, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
       dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnSimpanTTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanTTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSimpanTTEActionPerformed

    private void TPassphraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPassphraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPassphraseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            PassphraseBSRE dialog = new PassphraseBSRE(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpanTTE;
    private javax.swing.JLabel PassphraseBSRE;
    private widget.TextBox TPassphrase;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JTextField jTextField1;
    private widget.panelisi panelGlass6;
    // End of variables declaration//GEN-END:variables

    public void setTinggi(int tinggi){
        this.tinggi=tinggi;
    }
    
    public void setLebar(int lebar){
        this.lebar=lebar;
    }
    
    public void setNoKa(String noka){
        this.noka=noka;
    }
 
}
